aqua: https://huggingface.co/datasets/nguyen-brat/aqua
asdiv: https://huggingface.co/datasets/nguyen-brat/asdiv
clutrr: https://huggingface.co/datasets/CLUTRR/v1
date: https://huggingface.co/datasets/fanshiyu/date
gsm8k:
  url: https://huggingface.co/datasets/openai/gsm8k
  config: main
multiArith: https://huggingface.co/datasets/ChilleD/MultiArith
saycan: https://huggingface.co/datasets/chiayewken/saycan
qaSports: https://huggingface.co/datasets/PedroCJardim/QASports
strategyQA: https://huggingface.co/datasets/voidful/StrategyQA
svamp: https://huggingface.co/datasets/ChilleD/SVAMP